### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "aditya.kumar1@gmail.com",
  "password": "12345"
}

###Find a user by ID
GET http://localhost:3000/auth/3

###Find all users with given email
 GET http://localhost:3000/auth?email=abhijeet.kumar@gmail.com

###Delete a user
DELETE  http://localhost:3000/auth/5

### Update a user
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
  "password": "12346"
}